SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

CREATE TABLE users (
  id          INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name        VARCHAR(255) UNIQUE,
  password    VARCHAR(255)
  );
